### ISSUE TITLE
Upgrade CxxWrap version

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/OpenSpiel.jl#12]
The latest version of CxxWrap@v0.12 should work on Julia@v1.7 now.

**Comment by findmyway** [comment]
Tried to update the dependency. However, the built library can not be loaded correctly. 

Tried to update the dependency as suggested https://github.com/JuliaInterop/CxxWrap.jl/issues/319 but still can't load it.

**Comment by jonathan-laurent** [comment]
I believe this issue is keeping me from using OpenSpiel with Julia 1.7.
Indeed, CxxWrap v0.10 segfaults on Julia 1.7.
Any update on this?

**Comment by findmyway** [comment]
Well, you may not believe it. I just gave it a try again before the supper. And I think I figured out what was missing...

A new release should be tagged soon this weekend.

**Comment by findmyway** [comment]
@JuliaRegistrator register
