### ISSUE TITLE
unable to add wrapper to julia

### ISSUE THREAD

**Issue by irvincardoza** [JuliaReinforcementLearning/OpenSpiel.jl#24]
**The same problem exists on mac/windows and linux, as I verified on call platforms.**

julia> err
PkgPrecompileError: The following 1 direct dependency failed to precompile:

OpenSpiel [ceb70bd2-fe3f-44f0-b81f-41608acaf2f2]

Failed to precompile OpenSpiel [ceb70bd2-fe3f-44f0-b81f-41608acaf2f2] to "/home/irvin-cardoza/.julia/compiled/v1.10/OpenSpiel/jl_Uec8UG".
C++ exception while wrapping module OpenSpiel: **Type for PlayerAction was not found when mapping it.
ERROR: LoadError: Type for PlayerAction was not found when mapping it.**
Stacktrace:
 [1] register_julia_module
   @ ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:393 [inlined]
 [2] readmodule(so_path_cb::typeof(OpenSpiel_jll.get_libspieljl_path), funcname::Symbol, m::Module, flags::Nothing)
   @ CxxWrap.CxxWrapCore ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:751
 [3] wrapmodule(so_path_cb::Function, funcname::Symbol, m::Module, flags::Nothing)
   @ CxxWrap.CxxWrapCore ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:761
 [4] top-level scope
   @ ~/.julia/packages/OpenSpiel/fymb6/src/OpenSpiel.jl:8
 [5] include
   @ ./Base.jl:495 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2222
 [7] top-level scope
   @ stdin:3

_**Steps Taken to add wrapper**_

1. Installed Julia 
2. Cloned the OpenSpiel.jl repo (even tried to clone directly from julia pkg)
3. Tried the command     using OpenSpiel   , which resulted in the error
4. Even tried ] add OpenSpiel on linux and the error still existed

**I am trying to integrate AlphaZero.jl and build a machine learning project but I am stuck at this issue**

**Comment by findmyway** [comment]
It seems you are using the very latest version of OpenSpiel_jll.

I'll address it later today.

**Comment by irvincardoza** [comment]
Thank you, it worked now!
